import React,{useState,useEffect} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'react-phone-input-2/lib/style.css'
import PhoneInput from 'react-phone-input-2'
import 'react-phone-input-2/lib/style.css'
// import Image from 'react-bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';
import  $   from 'jquery';
import { useRouter } from 'next/router';
import logo from './Images/icon.png'; 4

export default function Home() {

    var router = useRouter();

const [phone,setPhone] = useState();

var item = setTimeout(()=>{

  $(document).ready(function(){
    $('.MainSplash').fadeOut();
    router.replace('./register');
  });

},2000);

function check(){
    router.push("/secondPage");
}

  return (
    <div className={styles.container}>
      <Head>
        <title>This is The Second Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <div className='MainSplash'>
<Image style={{borderRadius:'10px'}} height={200} width={200} src={logo} />
<div className="text-center">
<h1></h1>
<h1 className='text-white'>Prathistha</h1>
</div>
</div>
</main>
     
    </div>
  )
}
